In [31]:
import numpy as np
import pandas as pd

In [32]:
np.__version__

'1.21.5'

In [33]:
data = pd.read_csv('data.csv')

In [34]:
data.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

In [35]:
data[data['Make']=='Audi']

Make Model  Year             Engine Fuel Type  Engine HP  \
17     Audi   100  1992             regular unleaded      172.0   
18     Audi   100  1992             regular unleaded      172.0   
19     Audi   100  1992             regular unleaded      172.0   
20     Audi   100  1992             regular unleaded      172.0   
21     Audi   100  1992             regular unleaded      172.0   
...     ...   ...   ...                          ...        ...   
10901  Audi   TTS  2016  premium unleaded (required)      292.0   
10902  Audi   TTS  2017  premium unleaded (required)      292.0   
11178  Audi    V8  1992             regular unleaded      276.0   
11179  Audi    V8  1993             regular unleaded      276.0   
11180  Audi    V8  1994             regular unleaded      276.0   

       Engine Cylinders Transmission Type      Driven_Wheels  Number of Doors  \
17                  6.0            MANUAL  front wheel drive              4.0   
18                  6.0            MANUAL  front wheel drive              4.0   
19                  6.0         AUTOMATIC    all wheel drive              4.0   
20                  6.0            MANUAL  front wheel drive              4.0   
21                  6.0            MANUAL    all wheel drive              4.0   
...                 ...               ...                ...              ...   
10901               4.0  AUTOMATED_MANUAL    all wheel drive              2.0   
10902               4.0  AUTOMATED_MANUAL    all wheel drive              2.0   
11178               8.0         AUTOMATIC    all wheel drive              4.0   
11179               8.0         AUTOMATIC    all wheel drive              4.0   
11180               8.0         AUTOMATIC    all wheel drive              4.0   

                             Market Category Vehicle Size Vehicle Style  \
17                                    Luxury      Midsize         Sedan   
18                                    Luxury      Midsize         Sedan   
19                                    Luxury      Midsize         Wagon   
20                                    Luxury      Midsize         Sedan   
21                                    Luxury      Midsize         Sedan   
...                                      ...          ...           ...   
10901       Factory Tuner,Luxury,Performance      Compact         Coupe   
10902  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
11178                     Luxury,Performance      Midsize         Sedan   
11179                     Luxury,Performance      Midsize         Sedan   
11180                     Luxury,Performance      Midsize         Sedan   

       highway MPG  city mpg  Popularity   MSRP  
17              24        17        3105   2000  
18              24        17        3105   2000  
19              20        16        3105   2000  
20              24        17        3105   2000  
21              21        16        3105   2000  
...            ...       ...         ...    ...  
10901           27        23        3105  51900  
10902           27        23        3105  52500  
11178           18        13        3105   2000  
11179           18        13        3105   2149  
11180           18        13        3105   2239  

[328 rows x 16 columns]

In [36]:
data[data['Make']=='Audi']['Model'].nunique()

34

In [37]:
len(data)

11914

In [38]:
data.isnull().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders       30
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

In [39]:
data['Engine Cylinders'].median()

6.0

In [40]:
data['Engine Cylinders'].mode()

0    4.0
Name: Engine Cylinders, dtype: float64

In [41]:
data['Engine Cylinders'].fillna(4.0, inplace=True)

In [42]:
data['Engine Cylinders'].median()

6.0

In [43]:
lotus_cars = data[data['Make']=='Lotus'][['Engine HP', 'Engine Cylinders']]

In [44]:
lotus_cars = lotus_cars.drop_duplicates()

In [45]:
lotus_cars

Engine HP  Engine Cylinders
3912      189.0               4.0
3913      218.0               4.0
3918      217.0               4.0
4216      350.0               8.0
4257      400.0               6.0
4259      276.0               6.0
4262      345.0               6.0
4292      257.0               4.0
4293      240.0               4.0

In [46]:
X = lotus_cars.to_numpy()

In [47]:
X

array([[189.,   4.],
       [218.,   4.],
       [217.,   4.],
       [350.,   8.],
       [400.,   6.],
       [276.,   6.],
       [345.,   6.],
       [257.,   4.],
       [240.,   4.]])

In [48]:
X.T

array([[189., 218., 217., 350., 400., 276., 345., 257., 240.],
       [  4.,   4.,   4.,   8.,   6.,   6.,   6.,   4.,   4.]])

In [49]:
XTX = np.matmul(X.T, X)
XTX

array([[7.31684e+05, 1.34100e+04],
       [1.34100e+04, 2.52000e+02]])

In [50]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 5.53084235e-05, -2.94319825e-03],
       [-2.94319825e-03,  1.60588447e-01]])

In [51]:
y = np.array([1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800])
y

array([1100,  800,  750,  850, 1300, 1000, 1000, 1300,  800])

In [52]:
np.matmul(np.matmul(XTX_inv, X.T), y)

array([  4.59494481, -63.56432501])